<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!--If you are willing to use Windows/MacOS native APIs you will need to create 3 projects.
    One for Windows with net10.0-windows TFM, one for MacOS with net10.0-macos and one with net10.0 TFM for Linux.-->
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<EFScaffoldModelStage>publish</EFScaffoldModelStage>
	</PropertyGroup>

	<PropertyGroup>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tasks" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Avalonia.Desktop" />
		<PackageReference Include="ShowMeTheXaml.Avalonia" />
		<PackageReference Include="ShowMeTheXaml.Avalonia.Generator" />
	</ItemGroup>
	<ItemGroup>
		<AdditionalFiles Include="..\PromptCraft\**\*.axaml" />
		<AdditionalFiles Include="..\PromptCraft\**\*.xaml" />
		<AdditionalFiles Include="**\*.axaml" />
		<AdditionalFiles Include="**\*.xaml" />
	</ItemGroup>
	<!--<ItemGroup>
		<AvaloniaXaml Remove="Desktop.Styles\ShowMeTheXamlStyles.axaml" />
	</ItemGroup>
	<ItemGroup>
		<AdditionalFiles Update="Desktop.Styles\ShowMeTheXamlStyles.axaml">
			<SubType>Designer</SubType>
		</AdditionalFiles>
	</ItemGroup>-->
	<ItemGroup>
		<ProjectReference Include="..\PromptCraft\PromptCraft.csproj" />
	</ItemGroup>
</Project>
